/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelOverviewRouteImport } from './routes/panel.overview'
import { Route as PanelFormsRouteImport } from './routes/panel.forms'
import { Route as PanelBuilderRouteImport } from './routes/panel.builder'
import { Route as PanelAdminRouteImport } from './routes/panel.admin'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelOverviewRoute = PanelOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFormsRoute = PanelFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBuilderRoute = PanelBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/admin': typeof PanelAdminRoute
  '/panel/builder': typeof PanelBuilderRoute
  '/panel/forms': typeof PanelFormsRoute
  '/panel/overview': typeof PanelOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/admin': typeof PanelAdminRoute
  '/panel/builder': typeof PanelBuilderRoute
  '/panel/forms': typeof PanelFormsRoute
  '/panel/overview': typeof PanelOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/admin': typeof PanelAdminRoute
  '/panel/builder': typeof PanelBuilderRoute
  '/panel/forms': typeof PanelFormsRoute
  '/panel/overview': typeof PanelOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/panel'
    | '/panel/admin'
    | '/panel/builder'
    | '/panel/forms'
    | '/panel/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/panel'
    | '/panel/admin'
    | '/panel/builder'
    | '/panel/forms'
    | '/panel/overview'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/panel'
    | '/panel/admin'
    | '/panel/builder'
    | '/panel/forms'
    | '/panel/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/overview': {
      id: '/panel/overview'
      path: '/overview'
      fullPath: '/panel/overview'
      preLoaderRoute: typeof PanelOverviewRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/forms': {
      id: '/panel/forms'
      path: '/forms'
      fullPath: '/panel/forms'
      preLoaderRoute: typeof PanelFormsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/builder': {
      id: '/panel/builder'
      path: '/builder'
      fullPath: '/panel/builder'
      preLoaderRoute: typeof PanelBuilderRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin': {
      id: '/panel/admin'
      path: '/admin'
      fullPath: '/panel/admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelAdminRoute: typeof PanelAdminRoute
  PanelBuilderRoute: typeof PanelBuilderRoute
  PanelFormsRoute: typeof PanelFormsRoute
  PanelOverviewRoute: typeof PanelOverviewRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAdminRoute: PanelAdminRoute,
  PanelBuilderRoute: PanelBuilderRoute,
  PanelFormsRoute: PanelFormsRoute,
  PanelOverviewRoute: PanelOverviewRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
